version: "3"
networks:
#  rabbit:
#    driver: bridge
  db:
    driver: bridge

services:
  calendar_service:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    image: calendar_service_docker_image
    volumes:
      - ../configs/config.toml:/etc/calendar/config.toml:ro
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - db

  calendar_service_migration:
    image: calendar_service_docker_image
    command: goose -dir /migrations postgres "host=postgres user=sergey password=sergey dbname=calendar sslmode=disable" up
    depends_on:
      - postgres
      - calendar_service
    restart: on-failure    
    networks:
      - db

  postgres:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: sergey
      POSTGRES_PASSWORD: sergey
      POSTGRES_DB: calendar
    networks:
      - db

#  notification_service:
#    build: cmd/notification-service
#    depends_on:
#      - rabbit
#    restart: on-failure
#    environment:
#      NOTIFY_SERVICE_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
#    networks:
#      - rabbit



#  rabbit:
#    image: rabbitmq:3.7.17-management
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    expose:
#      - 15672
#    volumes:
#      - ./configs/rabbit.def.json:/etc/rabbitmq/definitions.json:ro
#      - ./configs/rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
#    networks:
#      - rabbit