[logger]
level = "INFO"

[storage]
type = "psql" # inmemory/psql

[psql]
dsn = "host=postgres port=5432 user=sergey password=sergey dbname=calendar sslmode=disable"

[http]
host = "0.0.0.0"
port = "8080"

[grpc]
host = "0.0.0.0"
port = "50001"