[logger]
level = "INFO"

[storage]
isinmemory = false

[psql]
dsn = "host=localhost port=5432 user=sergey password=sergey dbname=calendar sslmode=disable"

[http]
host = "127.0.0.1"
port = "8080"

[grpc]
host = "127.0.0.1"
port = "50001"