[logger]
level = "INFO"

[psql]
dsn = "host=localhost port=5432 user=sergey password=sergey dbname=calendar sslmode=disable"

[amqp]
uri = "amqp://guest:guest@localhost:5672/"
exchange = "calendar-exchange"
exchangeType = "direct"
key = "calendar-key"

[scheduler]
timeoutCheck = 5 # Second